version: '3.8'

networks:
  lingua_bridge:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: linguasage-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - lingua_bridge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  custom-server:
    image: povtemp/lingua
    container_name: linguasage-custom-server
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080" 
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/mydb?schema=public
      - JWTKEY=hello
    networks:
      - lingua_bridge
